apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-innlasting
  namespace: pensjonsamhandling
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8080
  team: {{team}}
  ingresses:
    - {{ingress}}
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/{{srvcluster}}/srvsamordning-hendelse-innlasting
        mountPath: /secret/serviceuser
      - kvPath: /kv/{{appcluster}}/fss/samordning-hendelse-innlasting/default
        mountPath: /var/run/secrets/nais.io/vault   
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics
