apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: samordning-hendelse-innlastning
  namespace: default
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/samordning-hendelse-innlastning:latest
  port: 8080
  team: teampeon
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi

